import { Resource, Langs, Kinds } from "../interfaces/resource";

export let db: Resource[] = [
    {
        id: 0,
        title: "THW choose the job they are passionate about.",
        url:new URL("https://www.youtube.com/watch?v=gyg5B2hMb5E"),
        lang: Langs.EN,
        kind: Kinds.Debates,
    },
    {
        id: 1,
        title: "Como debater moções de Economia com Pedro González",
        url:new URL("https://www.youtube.com/watch?v=6EPnQqTnzkI"),
        lang: Langs.PT,
        kind: Kinds.Recorded,
    },
    {
        id: 2,
        title: "Note taking for debaters and adjudicators by Noluthando Honono",
        url:new URL("https://youtu.be/9jpgDmXAAaA?t=7"),
        lang: Langs.EN,
        kind: Kinds.Debates,
    },
    {
        id: 3,
        title: "Contributing to panel discussions as a Wing or a Trainee by Matthew Conley Evans",
        url:new URL("https://youtu.be/M1fWwfRs8gg"),
        lang: Langs.EN,
        kind: Kinds.Recorded,
    },
    {
        id: 4,
        title: "Adjudication with Brian Wong",
        url:new URL("https://youtu.be/pvOfgVUXF6g"),
        lang: Langs.EN,
        kind: Kinds.Recorded,
    
    },
    {
        id: 5,
        title: "How to debate International Relations Motions",
        url:new URL("https://drive.google.com/file/d/1RtOe92PmEldvuac22ojdeJcnNDOXx__N/view?usp=drivesdk"),
        lang: Langs.EN,
        kind: Kinds.Written,
    },
    {
        id: 6,
        title: "What does a good judge believe in?",
        url:new URL("https://globaldebateblog.blogspot.com/2012/11/what-does-good-judge-believe-thoughts.html"),
        lang: Langs.EN,
        kind: Kinds.Articles,
    },
    {
        id: 7,
        title: "Arte por Fattha Mahmud",
        url:new URL("https://www.youtube.com/watch?v=kC-ESS0VAXk"),
        lang: Langs.PT,
        kind: Kinds.Recorded,
    },
    {
        id: 8,
        title: "How to win debates without really making arguments: An Introduction to Framing with Adam Hawksbee",
        url:new URL("https://www.youtube.com/watch?v=Xd_8jrid_mk"),
        lang: Langs.EN,
        kind: Kinds.Recorded,
    },
    {
        id: 9,
        title: "Debating China with Brian Wong",
        url:new URL("https://www.youtube.com/watch?v=XnI4d0oJWRo"),
        lang: Langs.EN,
        kind: Kinds.Recorded,
    },
    {
        id: 10,
        title: "How to be a good and useful wing",
        url:new URL("https://drive.google.com/file/d/1HQLuMe0Mo1_PiEr3ZONaEyPQ8bOadrr1/view?usp=drivesdk"),
        lang: Langs.EN,
        kind: Kinds.Written,
    },
    {
        id: 11,
        title: "WUDC Judging Manual",
        url:new URL("https://drive.google.com/file/d/1rg9gNHM9-oFDmRPToiX0f5vlVIZP6gXz/view?usp=drivesdk"),
        lang: Langs.EN,
        kind: Kinds.Manuals,
    },
    {
        id: 12,
        title: "Política com Gabriel Affonso",
        url:new URL("https://www.youtube.com/watch?v=FQ0yhMMv2hA&feature=youtu.be"),
        lang: Langs.PT,
        kind: Kinds.Recorded,
    },
    {
        id: 13,
        title: "Motion Setting and Evaluating",
        url:new URL("https://docs.google.com/document/u/0/d/1ZnLYmmvd_wom_u0EZk7JPXBBVtLsgACmA10oy7v68C8/mobilebasic"),
        lang: Langs.EN,
        kind: Kinds.Written,
    },
    {
        id: 14,
        title: "Análise de Moções e PrepTime com Bruno Santos",
        url:new URL("https://www.youtube.com/watch?v=flzgvS7tupY"),
        lang: Langs.PT,
        kind: Kinds.Recorded,
    },
    {
        id: 15,
        title: "Becoming Super Saiyan",
        url:new URL("https://ehpriori.com/home/becoming-super-saiyan"),
        lang: Langs.EN,
        kind: Kinds.Articles,
    },
    {
        id: 16,
        title: "Eh Priori",
        url:new URL("https://ehpriori.com/"),
        lang: Langs.EN,
        kind: Kinds.Websites,
    },
    {
        id: 17,
        title: "Hello, Motions!",
        url:new URL("http://hellomotions.com/"),
        lang: Langs.EN,
        kind: Kinds.Websites,
    },
    {
        id: 18,
        title: "The Breaker",
        url:new URL("https://the-breaker.netlify.app/"),
        lang: Langs.PT,
        kind: Kinds.Websites,
    },
    {
        id: 19,
        title: "Manual de Debates da SdDUFC",
        url:new URL("https://drive.google.com/file/d/1l7i3Jttb6oIqeU91rCUOcRX5vxarSTzs/view?usp=sharing"),
        lang: Langs.PT,
        kind: Kinds.Manuals,
    },
    {
        id: 20,
        title: "Whip Speaker with Helena Ivanov",
        url:new URL("https://www.youtube.com/watch?v=acXxhooa73c&feature=youtu.be"),
        lang: Langs.EN,
        kind: Kinds.Recorded,
    },
    {
        id: 21,
        title: "Primeiro Ministro e Líder da Oposição - Ary Ferreira da Cunha",
        url:new URL("https://www.youtube.com/watch?v=U5u_I0JZTj8"),
        lang: Langs.PT,
        kind: Kinds.Recorded,
    },
    {
        id: 22,
        title: "THBT the world's poor would be justified in pursuing complete Marxist revolution.",
        url:new URL("https://www.youtube.com/watch?v=tngaDNSlCpU"),
        lang: Langs.EN,
        kind: Kinds.Debates,
    },
    {
        id: 23,
        title: "THS Iran's extension of the Sharia principle of 'an eye for an eye' to the victims of acid attacks.",
        url:new URL("https://www.youtube.com/watch?v=RMEEZGoUmvI"),
        lang: Langs.EN,
        kind: Kinds.Debates,
    },
    {
        id: 24,
        title: "THBT governments should abandon the strategy of 'decapitation' in fighting terrorism.",
        url:new URL("https://www.youtube.com/watch?v=3WX-4i9FqvE"),
        lang: Langs.EN,
        kind: Kinds.Debates,
    },
    {
        id: 25,
        title: "Adjuntos - Frederico Oliveira",
        url:new URL("https://www.youtube.com/watch?v=PjZVa182LRo"),
        lang: Langs.PT,
        kind: Kinds.Recorded,
    },
    {
        id: 26,
        title: "Extensões - Diogo Videira",
        url:new URL("https://www.youtube.com/watch?v=AXON4hgCSkI"),
        lang: Langs.PT,
        kind: Kinds.Recorded,
    },
    {
        id: 27,
        title: "Whips - Hermione (Ana Cláudia Freitas)",
        url:new URL("https://www.youtube.com/watch?v=X3GUnYqWAP4"),
        lang: Langs.PT,
        kind: Kinds.Recorded,
    }
]